# load libraries
library("tidyverse")

# load data
co2_data <- read.csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")

# Q1: What is the total amount of CO2 emission in 1900? What about that in 2020?
# These two values can give our readers very descriptive information about hugely
# increased CO2 emission. Store the 1900 emission in `co2_1900`, and 2020 emission
# `co2_2020`.
co2_1900 <- co2_data %>%
  group_by(year) %>%
  summarise(total_emit = sum(co2, na.rm = TRUE)) %>%
  filter(year == 1900) %>%
  pull(total_emit)

co2_2020 <- co2_data %>%
  group_by(year) %>%
  summarise(total_emit = sum(co2, na.rm = TRUE)) %>%
  filter(year == 2020) %>%
  pull(total_emit)

# Q2: Compared with 1900, how many percentage has the total CO2 emission increased
# by in 2020? This CO2 percentage is very important in helping our readers
# understand how quickly the CO2 emission is increased over the past century,
# and how serious the current situation is. Store CO2 emission percentage in
# `co2_percent`.
co2_percent <- (co2_2020 - co2_1900) / co2_1900 * 100
co2_percent <- round(co2_percent, 3)

# Q3: Compared with 1900, how many percentage has the total population increased
# by in 2020? With the increased population percentage as comparison, our
# readers will have a more impressive feeling about increasing speed of CO2
# emission. Store population increase percentage in `peo_percent`.
peo_1900 <- co2_data %>%
  group_by(year) %>%
  summarise(total_peo = sum(population, na.rm = TRUE)) %>%
  filter(year == 1900) %>%
  pull(total_peo)

peo_2020 <- co2_data %>%
  group_by(year) %>%
  summarise(total_peo = sum(population, na.rm = TRUE)) %>%
  filter(year == 2020) %>%
  pull(total_peo)

peo_percent <- (peo_2020 - peo_1900) / peo_1900 * 100
peo_percent <- round(peo_percent, 3)

# Q4: In 2020, among coal, gas, oil, which kind of fuel occupies the highest
# proportion of CO2 emission? This result is a very good indicator for our readers
# to understand which kind of fuel is the worst regarding CO2 emission problem.
# Also, to reduce CO2 emission effectively, which kind of fuel shall we focus on
# to eliminate. Store this type of fuel in `fuel_most_co2`.
fuel_co2 <- co2_data %>%
  group_by(year) %>%
  summarise(coal = sum(coal_co2, na.rm = TRUE),
            gas = sum(gas_co2, na.rm = TRUE),
            oil = sum(oil_co2, na.rm = TRUE)) %>%
  filter(year == 2020) %>%
  select(coal, gas, oil)

fuel_co2 <- sort(fuel_co2, decreasing = TRUE)
fuel_most_co2 <- names(fuel_co2[1])

# Q5: From 1900 to 2020, among coal, gas, oil, is the proportion of coal usage
# increased or decreased? By how many percentage? Calculate this by amount of co2
# generated by coal, gas, and oil. We already know that the coal contributes the
# most to co2 emission in 2020 among coal, gas, and oil; Thus, it is very
# meaningful to check the proportion change of coal usage, which is a good indicator
# showing whether the situation becomes better or worse: compared with 100 years
# ago, do we depend more heavily on coals? Store this proportion change in
# `coal_prop_change`.
coal_prop_2020 <- fuel_co2['coal'] / sum(fuel_co2)

fuel_co2_1900 <- co2_data %>%
  group_by(year) %>%
  summarise(coal = sum(coal_co2, na.rm = TRUE),
            gas = sum(gas_co2, na.rm = TRUE),
            oil = sum(oil_co2, na.rm = TRUE)) %>%
  filter(year == 1900) %>%
  select(coal, gas, oil)
coal_prop_1900 <- fuel_co2_1900['coal'] / sum(fuel_co2_1900)

coal_prop_change <- (coal_prop_2020 - coal_prop_1900) / coal_prop_1900 * 100
coal_prop_change <- pull(coal_prop_change, coal)
coal_prop_change <- round(coal_prop_change, 3)

# server setup
server <- function(input, output) {
  output$q1a <- renderText({
    msg <- paste0("year 1900 = ", co2_1900)
    return(msg)
  })
  output$q1b <- renderText({
    msg <- paste0("year 2020 = ", co2_2020)
    return(msg)
  })
  output$q2 <- renderText({
    return(paste0("CO2 emission increase percentage = ", co2_percent, "%"))
  })
  output$q3 <- renderText({
    return(paste0("population increase percentage = ", peo_percent, "%"))
  })
  output$q4 <- renderText({
    return(paste("fuel contributes the most to CO2 emission =", fuel_most_co2))
  })
  output$q5 <- renderText({
    return(paste0("proportion of coal usage is decreased by ", coal_prop_change, "%"))
  })
  
  # plot analysis: Create a plot analyzing trends of CO2 emission amount from coal,
  # gas, and oil from 1850 and 2020.
  # Here, we do the data preparation, and will do the plotting below.
  fuels_co2_emit <- reactive({
    co2_data %>%
    group_by(year) %>%
    filter(year >= input$year_s[1] & year <= input$year_s[2]) %>%
    summarise(coal_t = sum(coal_co2, na.rm = TRUE),
              gas_t = sum(gas_co2, na.rm = TRUE),
              oil_t = sum(oil_co2, na.rm = TRUE)) %>%
    select(year, coal_t, gas_t, oil_t)
  })
  
  output$plot_all <- renderPlotly({
    fuels_emit_plot_all <- ggplot(data = fuels_co2_emit()) +
      geom_line(aes(y = coal_t, x = year, colour = "Coal")) +
      geom_line(aes(y = gas_t, x = year, colour = "Gas")) +
      geom_line(aes(y = oil_t, x = year, colour = "Oil")) +
      labs(x = "Year", y = "CO2 Emission Amount", title = "CO2 Emission Amount By Years (Coal, Gas, Oil)") +
      scale_color_manual(
        name = "line of",
        values = c("Coal" = "red", "Gas" = "blue", "Oil" = "green")
      )
    fuels_emit_plotly_all <- ggplotly(fuels_emit_plot_all)
    return(fuels_emit_plotly_all)
  })
  output$plot <- renderPlotly({
    fuels_emit_plot <- ggplot(data = fuels_co2_emit()) +
      geom_line(aes(y = !!as.name(input$fuel_type), x = year)) +
      labs(x = "Year", y = "CO2 Emission Amount", title = "CO2 Emission Amount By Years (Coal, Gas, Oil)")
    fuels_emit_plotly <- ggplotly(fuels_emit_plot)
    return(fuels_emit_plotly)
  })
}