introduction <- tabPanel(
  "Introduction",
  fluidPage(
    h1("Introduction & Summary Information"),
    p("Nowadays, as global warming becomes more serious, people have been 
      focusing more on the CO2 emission problem, the main source of global 
      warming. Therefore, in this research, we will analyze this problem with the
      following variables in owid-co2-data dataset."),
    tags$ul(
      tags$li("year: Year of observation"),
      tags$li("co2: Annual production-based emissions of carbon dioxide (CO2)"),
      tags$li("coal_co2: Annual production-based emissions of carbon dioxide (CO2) from coal"),
      tags$li("gas_co2: nnual production-based emissions of carbon dioxide (CO2) from gas"),
      tags$li("oil_co2: Annual production-based emissions of carbon dioxide (CO2) from oil"),
      tags$li("population: Population by country")
    ),
    p("During the analysis, it is very meaningful to observe the change of CO2 
      data over years, so we choose \"year\" and \"co2\" from dataset. Also, by
      comparing the change of CO2 with that of population, our readers can get
      more sense about how quickly the CO2 emission increases, so we choose \"population\"
      from dataset. Finally, we want to research among main energy resources, 
      coal, gas, oil, which is more important regarding reducing CO2 emission; thus, 
      we also choose \"coal_co2\", \"gas_co2\", \"oil_co2\" from dataset."),
    p("Per these aspects above, here are some key indices as reference."),
    tags$ul(
      tags$li("What is the total amount of CO2 emission in 1900? What 
              about that in 2020?"),
      tags$b("Answer:"),
      textOutput(outputId = "q1a"),
      textOutput(outputId = "q1b"),
      tags$li("Compared with 1900, how many percentage has the total CO2 
              emission increased by in 2020?"),
      tags$b("Answer:"),
      textOutput(outputId = "q2"),
      tags$li("Compared with 1900, how many percentage has the total population 
              increased by in 2020?"),
      tags$b("Answer:"),
      textOutput(outputId = "q3"),
      tags$li("In 2020, among coal, gas, oil, which kind of fuel occupies the 
              highest proportion of CO2 emission?"),
      tags$b("Answer:"),
      textOutput(outputId = "q4"),
      tags$li("From 1900 to 2020, among coal, gas, oil, is the proportion of
              coal usage increased or decreased? By how many percentage?"),
      tags$b("Answer:"),
      textOutput(outputId = "q5"),
    )
  )
)

plot_sidebar <- sidebarPanel(
  selectInput(
    inputId = "fuel_type",
    label = "Fuel Type",
    choices = list("All",
                   "Coal" = "coal_t",
                   "Gas" = "gas_t",
                   "Oil" = "oil_t"),
    selected = "All"
  ),
  sliderInput(
    inputId = "year_s",
    label = "Year",
    min = 1850,
    max = 2020,
    value = c(1850, 2020)
  )
)


plot_main <- mainPanel(
  conditionalPanel(
    condition = "input.fuel_type == 'All'",
    plotlyOutput(outputId = "plot_all")
  ),
  conditionalPanel(
    condition = "input.fuel_type != 'All'",
    plotlyOutput(outputId = "plot")
  )
)

co2_vis <- tabPanel(
  "Fuels CO2 Emission Visualization",
  sidebarLayout(
    plot_sidebar,
    plot_main
  ),
  fluidPage(
    p("The reason we include this chart is that by comparing CO2 emission amount 
      from coal, gas, and oil from 1850 and 2020, we can give our readers very 
      impressive feeling about during past 150 yeears, which kind of fuel is the
      main source of CO2 emission. This will inspire our readers to think about
      to reduce CO2 emission problem most effectively, which kind of fuel we shall
      pay more attention to, and which another kind of fuel can serve as a good
      substituion."),
    p("From our chart, we can see that over past 150 years, coals are the main 
      source of CO2 emission, and CO2 emission amount of oil is catching up. Two 
      possible reasons are 1) these two fuels are discovered and utilized earlier 
      than gas, so they are used more and generate more CO2; 2) these two fuels 
      are less \"clean\" than gas, which means that burning same amount of them 
      and gas, the amount of CO2 generated by coal and oil is way much more than 
      that by gas. Of course, these two possible reasons about patterns are 
      hypothesis needed further research, which is another good inpiration to our 
      readers")
  )
)

ui <- navbarPage(
  "CO2 Analysis",
  introduction,
  co2_vis
)